x-image: &default_image apartmentlinesproduction/transcription-pipeline:v0.1.0
x-shared-volumes: &shared-volumes
  - .:/usr/src/transcription-pipeline

x-secrets-environment: &secrets_environment
  # HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
  TRANSCRIPTION_API_KEY: ${TRANSCRIPTION_API_KEY}
  TRANSCRIPTION_DOMAIN: ${TRANSCRIPTION_DOMAIN}

x-command: &default_command [ "transcription-processor", "--limit", "1000", "--processing-limit", "2" ]

services:
  transcription-local-service:
    environment:
      <<:
        - *secrets_environment
    image: *default_image
    command: *default_command
    volumes: *shared-volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
