version: '3'

x-python-image: &default_python_image python:3.12.9-bookworm
x-networks: &default_networks
  - transcription-pipeline-network

x-build: &default_build
  context: .
  dockerfile: Dockerfile
  args:
    BASE_IMAGE: *default_python_image

x-secrets-environment: &secrets_environment
  TRANSCRIPTION_API_KEY: ${TRANSCRIPTION_API_KEY}
  TRANSCRIPTION_DOMAIN: ${TRANSCRIPTION_DOMAIN}

x-command: &default_command [ "transcription-processor", "--limit", "1000", "--processing-limit", "2", "--debug" ]

services:
  transcription-processor:
    build:
      <<: *default_build
    environment:
      <<:
        - *secrets_environment
    command: *default_command
    networks: *default_networks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  transcription-pipeline-network:
